name: Deploy Plugin to WP Engine

on:
  push:
    branches:
      - main   # Change to 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: aimegroup
          SRC_PATH: "."
          REMOTE_PATH: wp-content/plugins/fuse-registration/
          FLAGS: --exclude=".git/" --exclude=".github/" --exclude="*.zip"
